config {
  type: "view",
  schema: "staging",
  description: "A cleaned version of sources.stackoverflow.posts_answers table"
}

SELECT
  id as post_id,
  creation_date as created_at,
  'answer' as type,
  title,
  body,
  owner_user_id,
  cast(parent_id as string) as parent_id
FROM
  ${ref("posts_answers")}
WHERE
  -- limit to recent data for the purposes of this demo project
  creation_date >= timestamp("2019-01-01")
